// Fallback product data for when APIs are not available
export const fallbackProducts = [
  {
    id: "rec123",
    name: "Modern Sofa - Ghana Edition",
    price: 1500,
    category: "sofas",
    description: "A beautiful modern sofa perfect for Ghanaian homes. Crafted with premium materials and designed for comfort and style. Features durable fabric upholstery and solid wooden frame construction.",
    image: "/src/assets/basketChair.webp",
    images: [
      { url: "/src/assets/basketChair.webp" },
      { url: "/src/assets/basketChair.webp" },
      { url: "/src/assets/basketChair.webp" }
    ],
    colors: ["blue"],
    company: "Ghana Furniture Co",
    featured: true,
    shipping: true,
    stock: 5,
    stars: 4.5,
    reviews: 23,
    material: "Premium Fabric",
    designer: "Kwame Asante",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec124",
    name: "Dining Table - Ashanti Style", 
    price: 1200,
    category: "dining",
    description: "Elegant dining table inspired by traditional Ashanti craftsmanship. Made from locally sourced hardwood with intricate carved details. Perfect for family gatherings and entertaining guests.",
    image: "/src/assets/light1.webp",
    images: [
      { url: "/src/assets/light1.webp" },
      { url: "/src/assets/light1.webp" }
    ],
    colors: ["brown"],
    company: "Accra Woodworks",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.2,
    reviews: 15,
    material: "Hardwood",
    designer: "Ama Osei",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec125",
    name: "Traditional Chair - Kente Pattern",
    price: 800,
    category: "lounge chairs",
    description: "Beautiful chair featuring traditional Kente pattern design. Combines cultural heritage with modern comfort. Hand-woven fabric seat with solid wooden frame construction.",
    image: "/src/assets/light2.webp",
    images: [
      { url: "/src/assets/light2.webp" },
      { url: "/src/assets/light2.webp" }
    ],
    colors: ["red"],
    company: "Kumasi Crafts",
    featured: true,
    shipping: true,
    stock: 8,
    stars: 4.8,
    reviews: 32,
    material: "Kente Fabric & Wood",
    designer: "Kofi Mensah",
    bestseller: true,
    new_arrival: false,
    sale: true,
    trending: true
  },
  {
    id: "rec126",
    name: "Wooden Janus Table Lamp",
    price: 1100,
    category: "lighting",
    description: "Contemporary wooden table lamp with adjustable brightness settings. Features sustainable wood construction combined with modern LED technology. Perfect for reading and ambient lighting.",
    image: "/api/placeholder/400/400",
    images: [
      { url: "/api/placeholder/400/400" },
      { url: "/api/placeholder/400/400" },
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["brown"],
    company: "Accra Lighting Co",
    featured: true,
    shipping: true,
    stock: 5,
    stars: 4.8,
    reviews: 18,
    material: "Teak Wood",
    designer: "Nana Akoto",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec127",
    name: "Table Lamp For Desk",
    price: 270,
    category: "lighting", 
    description: "Modern wooden desk lamp with adjustable arm and energy-efficient LED bulb. Perfect for office work, studying, and task lighting. Features touch-sensitive controls and multiple brightness levels.",
    image: "/api/placeholder/400/400",
    images: [
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["brown"],
    company: "Kumasi Designs",
    featured: false,
    shipping: true,
    stock: 12,
    stars: 4.3,
    reviews: 9,
    material: "Pine Wood",
    designer: "Efua Asante",
    bestseller: false,
    new_arrival: false,
    sale: false,
    trending: false
  },
  {
    id: "rec128",
    name: "Under Dressing Table Kit",
    price: 720,
    category: "furniture",
    description: "Complete wooden dressing table set with mirror and multiple storage compartments. Crafted from premium hardwood with elegant finishing. Includes adjustable mirror and organized drawer system.",
    image: "/api/placeholder/400/400",
    images: [
      { url: "/api/placeholder/400/400" },
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["brown"],
    company: "Ghana Woodworks",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.6,
    reviews: 31,
    material: "Mahogany Wood",
    designer: "Kwame Osei",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec129",
    name: "Stage Floor Lamp",
    price: 330,
    category: "lighting",
    description: "Industrial-style wooden floor lamp with adjustable height mechanism. Perfect for living rooms, reading corners, and modern spaces. Combines contemporary aesthetics with practical functionality.",
    image: "/api/placeholder/400/400",
    images: [
      { url: "/api/placeholder/400/400" },
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["black"],
    company: "Accra Modern",
    featured: true,
    shipping: true,
    stock: 4,
    stars: 4.7,
    reviews: 22,
    material: "Ash Wood",
    designer: "Aba Mensah",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: true
  },
  {
    id: "rec130",
    name: "Single Speaker Ring",
    price: 200,
    category: "decoration",
    description: "Handcrafted wooden speaker enclosure with premium acoustic properties. Perfect blend of aesthetic appeal and high-quality sound reproduction. Ideal for audiophiles who appreciate natural materials.",
    image: "/api/placeholder/400/400", 
    images: [
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["brown"],
    company: "Tamale Audio",
    featured: false,
    shipping: true,
    stock: 6,
    stars: 4.1,
    reviews: 8,
    material: "Walnut Wood",
    designer: "Abdul Rahman",
    bestseller: false,
    new_arrival: false,
    sale: false,
    trending: false
  },
  // Additional products for better category coverage
  {
    id: "rec131",
    name: "Architect Floor Lamp",
    price: 450,
    category: "architect",
    description: "Professional architect-style floor lamp with adjustable arms and premium LED lighting. Perfect for design studios and modern offices.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Accra Design Studio",
    featured: true,
    shipping: true,
    stock: 7,
    stars: 4.6,
    reviews: 14,
    material: "Aluminum & Steel",
    designer: "Kofi Architect",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec132",
    name: "Decorative Wall Art",
    price: 150,
    category: "decoration",
    description: "Beautiful handcrafted wall art featuring traditional Ghanaian motifs. Perfect for adding cultural elegance to any space.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["blue"],
    company: "Kumasi Arts",
    featured: true,
    shipping: true,
    stock: 12,
    stars: 4.4,
    reviews: 28,
    material: "Canvas & Wood",
    designer: "Ama Cultural Arts",
    bestseller: true,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec133", 
    name: "Executive Office Chair",
    price: 950,
    category: "lounge chairs",
    description: "Premium executive office chair with ergonomic design and leather upholstery. Built for comfort during long work sessions.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Accra Office Solutions",
    featured: true,
    shipping: true,
    stock: 4,
    stars: 4.9,
    reviews: 35,
    material: "Genuine Leather",
    designer: "Professional Designs Ltd",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec134",
    name: "Modern Architect Desk",
    price: 1800,
    category: "architect",
    description: "Sleek modern architect desk with built-in storage and cable management. Perfect for creative professionals and home offices.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["brown"],
    company: "Ghana Modern Furniture",
    featured: false,
    shipping: true,
    stock: 2,
    stars: 4.7,
    reviews: 12,
    material: "Oak Wood & Steel",
    designer: "Modern Design Co",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec135",
    name: "Handwoven Basket Set",
    price: 85,
    category: "decoration",
    description: "Set of three handwoven baskets made from local materials. Perfect for storage and home decoration with authentic Ghanaian craftsmanship.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["brown"],
    company: "Northern Crafts Co",
    featured: false,
    shipping: true,
    stock: 15,
    stars: 4.2,
    reviews: 22,
    material: "Woven Grass & Bamboo",
    designer: "Traditional Crafts",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  // Additional products to reach 22 products like the target
  {
    id: "rec136",
    name: "Modern Sofa Set",
    price: 7700,
    category: "sofas",
    description: "Luxury 3-seater sofa with premium fabric upholstery. Contemporary design perfect for modern living rooms.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Ghana Luxury Furniture",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.8,
    reviews: 45,
    material: "Premium Fabric",
    designer: "Modern Living Co",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec137",
    name: "Vintage Dining Set",
    price: 5200,
    category: "dining",
    description: "Classic 6-seater dining table with matching chairs. Crafted from solid wood with vintage finish.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["brown"],
    company: "Vintage Crafts Ghana",
    featured: false,
    shipping: true,
    stock: 2,
    stars: 4.5,
    reviews: 18,
    material: "Solid Wood",
    designer: "Heritage Designs",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec138",
    name: "Professional Office Desk",
    price: 3200,
    category: "furniture",
    description: "Spacious office desk with built-in drawers and cable management. Perfect for home offices and workspaces.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["red"],
    company: "Office Pro Ghana",
    featured: false,
    shipping: true,
    stock: 8,
    stars: 4.3,
    reviews: 25,
    material: "Engineered Wood",
    designer: "Workspace Solutions",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec139",
    name: "Designer Floor Lamp",
    price: 890,
    category: "lighting",
    description: "Contemporary floor lamp with adjustable height and dimmer switch. Adds elegance to any room.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Illumina Ghana",
    featured: true,
    shipping: true,
    stock: 12,
    stars: 4.6,
    reviews: 33,
    material: "Metal & Fabric",
    designer: "Light Studio",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec140",
    name: "Ergonomic Lounge Chair",
    price: 2100,
    category: "lounge chairs",
    description: "Comfortable lounge chair with ergonomic support. Perfect for reading corners and relaxation areas.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["blue"],
    company: "Comfort Zone Ghana",
    featured: false,
    shipping: true,
    stock: 6,
    stars: 4.4,
    reviews: 19,
    material: "Memory Foam & Fabric",
    designer: "Ergonomic Designs",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: false
  },
  {
    id: "rec141",
    name: "Decorative Mirror Set",
    price: 320,
    category: "decoration",
    description: "Set of three decorative mirrors in different sizes. Adds depth and light to any space.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["blue"],
    company: "Mirror Magic Ghana",
    featured: false,
    shipping: true,
    stock: 18,
    stars: 4.1,
    reviews: 14,
    material: "Glass & Metal",
    designer: "Reflection Studios",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec142",
    name: "Architect Drafting Table",
    price: 4500,
    category: "architect",
    description: "Professional drafting table with adjustable angle and height. Essential for architects and designers.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["red"],
    company: "Pro Architect Ghana",
    featured: true,
    shipping: true,
    stock: 4,
    stars: 4.9,
    reviews: 28,
    material: "Steel & Wood",
    designer: "Professional Studios",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  // Additional products to reach 22 total
  {
    id: "rec143",
    name: "Luxury Bookshelf",
    price: 2800,
    category: "furniture",
    description: "5-tier wooden bookshelf with elegant design. Perfect for libraries and study rooms.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["brown"],
    company: "Library Crafts Ghana",
    featured: false,
    shipping: true,
    stock: 7,
    stars: 4.3,
    reviews: 21,
    material: "Solid Wood",
    designer: "Study Solutions",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec144",
    name: "Pendant Light Set",
    price: 650,
    category: "lighting",
    description: "Set of 3 modern pendant lights with adjustable height. Perfect for kitchen islands and dining areas.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Pendant Pro Ghana",
    featured: true,
    shipping: true,
    stock: 9,
    stars: 4.5,
    reviews: 17,
    material: "Metal & Glass",
    designer: "Hanging Lights Co",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec145",
    name: "Reclining Chair",
    price: 3500,
    category: "lounge chairs",
    description: "Comfortable reclining chair with footrest. Perfect for relaxation and watching TV.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["brown"],
    company: "Comfort First Ghana",
    featured: false,
    shipping: true,
    stock: 5,
    stars: 4.7,
    reviews: 31,
    material: "Leather & Steel",
    designer: "Relax Designs",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec146",
    name: "Wall Art Canvas",
    price: 180,
    category: "decoration",
    description: "Abstract wall art canvas with modern design. Adds personality to any room.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["blue"],
    company: "Art Hub Ghana",
    featured: false,
    shipping: true,
    stock: 25,
    stars: 4.2,
    reviews: 12,
    material: "Canvas & Frame",
    designer: "Modern Art Studio",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec147",
    name: "L-Shaped Sofa",
    price: 8900,
    category: "sofas",
    description: "Spacious L-shaped sofa for large living rooms. Seats 6-7 people comfortably.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black"],
    company: "Big Sofa Ghana",
    featured: true,
    shipping: true,
    stock: 2,
    stars: 4.9,
    reviews: 38,
    material: "Premium Fabric",
    designer: "Large Living Co",
    bestseller: true,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec148",
    name: "Bar Stool Set",
    price: 420,
    category: "lounge chairs",
    description: "Set of 2 adjustable bar stools with swivel function. Perfect for kitchen counters.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["red"],
    company: "Bar Furniture Ghana",
    featured: false,
    shipping: true,
    stock: 16,
    stars: 4.1,
    reviews: 23,
    material: "Metal & Plastic",
    designer: "Counter Solutions",
    bestseller: false,
    new_arrival: false,
    sale: false,
    trending: false
  }
];

// Helper function to get a single product by ID
export const getFallbackProductById = (id) => {
  return fallbackProducts.find(product => product.id === id) || null;
};

// Helper function to get featured products
export const getFeaturedProducts = () => {
  return fallbackProducts.filter(product => product.featured);
};

// Helper function to get new arrival products
export const getNewArrivalProducts = () => {
  return fallbackProducts.filter(product => product.new_arrival);
};

// Helper function to get bestseller products
export const getBestsellerProducts = () => {
  return fallbackProducts.filter(product => product.bestseller);
};