// Agricultural equipment data for Mest Technologies platform
import BasketChair from "../assets/basketChair.webp"
import Light1 from "../assets/light1.webp"
import Light2 from "../assets/light2.webp"

export const fallbackProducts = [
  {
    id: "rec123",
    name: "IPM Macroscope - Plant Disease Detection System",
    price: 8500,
    category: "Plant Health",
    description: "Advanced plant disease detection and identification system perfect for Ghanaian crop monitoring. Features high-resolution imaging, AI-powered disease recognition, and field-portable design. Includes comprehensive disease database and mobile app connectivity.",
    image: BasketChair,
    images: [
      { url: BasketChair },
      { url: BasketChair },
      { url: "/src/assets/basketChair.webp" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Mest AgriTech Solutions",
    featured: true,
    shipping: true,
    stock: 5,
    stars: 4.5,
    reviews: 23,
    material: "Weather-resistant ABS plastic",
    designer: "Agricultural Engineering Team",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec124",
    name: "Watchdog 2550 Wind Station - Professional Weather Monitoring", 
    price: 12500,
    category: "Weather Monitoring",
    description: "Professional-grade weather station designed for Ghanaian agricultural conditions. Monitors wind speed, direction, temperature, humidity, and rainfall. Features cellular connectivity, solar power, and weatherproof housing rated IP67.",
    image: Light1,
    images: [
      { url: Light1 },
      { url: "/src/assets/light1.webp" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Precision Agri Accra Ltd",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.2,
    reviews: 15,
    material: "Anodized aluminum with UV-resistant coating",
    designer: "Weather Systems Engineering",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec125",
    name: "SoilMaster Pro pH Kit - Advanced Soil Analysis",
    price: 1800,
    category: "Soil & Water",
    description: "Comprehensive soil analysis system for precision agriculture in Ghana. Measures pH, nutrient levels, organic matter, and soil conductivity. Features digital display, GPS logging, and smartphone connectivity for data management.",
    image: Light2,
    images: [
      { url: Light2 },
      { url: "/src/assets/light2.webp" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Kumasi Agricultural Instruments",
    featured: true,
    shipping: true,
    stock: 8,
    stars: 4.8,
    reviews: 32,
    material: "Ruggedized plastic with waterproof seals",
    designer: "Soil Science Laboratory",
    bestseller: true,
    new_arrival: false,
    sale: true,
    trending: true
  },
  {
    id: "rec126",
    name: "AquaSense Water Monitor - Multi-Parameter Testing",
    price: 3200,
    category: "Soil & Water",
    description: "Professional water quality monitoring system for irrigation and aquaculture applications. Measures pH, dissolved oxygen, turbidity, temperature, and conductivity. Features waterproof design, data logging, and smartphone connectivity.",
    image: "https://images.unsplash.com/photo-1551836022-8b2858c9c69b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    images: [
      { url: "https://images.unsplash.com/photo-1551836022-8b2858c9c69b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
      { url: "https://images.unsplash.com/photo-1558618996-fcd5c8cd8c93?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
      { url: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Hydro Systems Ghana",
    featured: true,
    shipping: true,
    stock: 5,
    stars: 4.8,
    reviews: 18,
    material: "Titanium sensors with ABS housing",
    designer: "Water Quality Engineering",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec127",
    name: "NutriTrack Fertilizer Analyzer - Rapid NPK Testing",
    price: 950,
    category: "Nutrient Management", 
    description: "Portable nutrient analyzer for real-time NPK testing in field conditions. Features rapid analysis, digital readout, and calibration for Ghanaian soil types. Perfect for precision fertilizer application and cost optimization.",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    images: [
      { url: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "AgriNutrient Systems",
    featured: false,
    shipping: true,
    stock: 12,
    stars: 4.3,
    reviews: 9,
    material: "Impact-resistant polycarbonate",
    designer: "Nutrient Analysis Lab",
    bestseller: false,
    new_arrival: false,
    sale: false,
    trending: false
  },
  {
    id: "rec128",
    name: "LabPro Precision Scale - High-Accuracy Weighing",
    price: 2400,
    category: "Lab Equipment",
    description: "Professional analytical balance for laboratory applications and field research. Features 0.1mg precision, internal calibration, and environmental controls. Ideal for soil sample preparation and chemical analysis.",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80",
    images: [
      { url: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
      { url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Laboratory Equipment Ghana",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.6,
    reviews: 31,
    material: "Stainless steel with anti-vibration base",
    designer: "Precision Instruments Division",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec129",
    name: "PlantVision Health Scanner - AI-Powered Crop Monitoring",
    price: 6800,
    category: "Plant Health",
    description: "Advanced crop health monitoring system with AI-powered disease detection. Features multispectral imaging, GPS mapping, and automated reporting. Perfect for early disease detection and crop optimization in Ghanaian agriculture.",
    image: "/api/placeholder/400/400",
    images: [
      { url: "/api/placeholder/400/400" },
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Smart Agriculture Ghana",
    featured: true,
    shipping: true,
    stock: 4,
    stars: 4.7,
    reviews: 22,
    material: "Carbon fiber with protective housing",
    designer: "AI Agriculture Research Team",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: true
  },
  {
    id: "rec130",
    name: "Test Strip Consumables Kit - Multi-Parameter Analysis",
    price: 150,
    category: "Consumables",
    description: "Comprehensive test strip kit for soil and water analysis. Includes pH strips, nitrate tests, phosphorus indicators, and potassium measurement tools. Essential consumables for regular monitoring and calibration maintenance.",
    image: "/api/placeholder/400/400", 
    images: [
      { url: "/api/placeholder/400/400" }
    ],
    colors: ["black", "white", "gray", "green"],
    company: "Northern Ghana Lab Supplies",
    featured: false,
    shipping: true,
    stock: 6,
    stars: 4.1,
    reviews: 8,
    material: "Chemical-resistant paper strips",
    designer: "Laboratory Standards Division",
    bestseller: false,
    new_arrival: false,
    sale: false,
    trending: false
  },
  // Additional agricultural equipment for comprehensive coverage
  {
    id: "rec131",
    name: "GreenHouse Climate Controller - Automated Environment System",
    price: 4500,
    category: "Weather Monitoring",
    description: "Advanced greenhouse climate control system with automated temperature, humidity, and ventilation management. Features smartphone connectivity and weather integration for optimal growing conditions.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Climate Systems Ghana",
    featured: true,
    shipping: true,
    stock: 7,
    stars: 4.6,
    reviews: 14,
    material: "Weather-resistant polymer housing",
    designer: "Environmental Control Team",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec132",
    name: "Drone Agricultural Sprayer - Precision Application",
    price: 15000,
    category: "Plant Health",
    description: "Professional agricultural drone with precision spraying capabilities. GPS-guided application for pesticides, fertilizers, and water. Features flight planning software and obstacle avoidance.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Drone Agriculture Ghana",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.8,
    reviews: 18,
    material: "Carbon fiber composite",
    designer: "Precision Agriculture Division",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec133", 
    name: "Solar-Powered Irrigation Controller - Smart Water Management",
    price: 2800,
    category: "Soil & Water",
    description: "Solar-powered irrigation control system with moisture sensors and automated scheduling. Reduces water usage by up to 40% while optimizing crop yield through precision watering.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Solar AgriTech Accra",
    featured: true,
    shipping: true,
    stock: 8,
    stars: 4.7,
    reviews: 25,
    material: "Solar panel with waterproof control unit",
    designer: "Sustainable Agriculture Systems",
    bestseller: true,
    new_arrival: false,
    sale: true,
    trending: true
  },
  {
    id: "rec134",
    name: "Livestock Health Monitor - Continuous Animal Tracking",
    price: 850,
    category: "Plant Health",
    description: "Wearable health monitoring system for cattle and sheep. Tracks vital signs, location, and behavior patterns. Features early disease detection and mobile app integration.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Livestock Tech Ghana",
    featured: false,
    shipping: true,
    stock: 15,
    stars: 4.4,
    reviews: 12,
    material: "Durable silicone with GPS module",
    designer: "Animal Health Solutions",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec135",
    name: "Seed Germination Chamber - Controlled Environment Testing",
    price: 3200,
    category: "Lab Equipment",
    description: "Professional seed germination testing chamber with precise temperature and humidity control. Essential for seed quality testing and research applications in agricultural laboratories.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Research Labs Ghana",
    featured: true,
    shipping: true,
    stock: 4,
    stars: 4.9,
    reviews: 22,
    material: "Stainless steel with glass observation window",
    designer: "Agricultural Research Division",
    bestseller: false,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec136",
    name: "Fish Pond Aerator System - Aquaculture Optimization",
    price: 1850,
    category: "Soil & Water",
    description: "High-efficiency pond aerator system for fish farming. Increases dissolved oxygen levels, improves water circulation, and supports higher fish density for better yields.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Aqua Systems Ghana",
    featured: true,
    shipping: true,
    stock: 6,
    stars: 4.6,
    reviews: 19,
    material: "Corrosion-resistant aluminum",
    designer: "Aquaculture Engineering",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  },
  {
    id: "rec137",
    name: "Grain Moisture Analyzer - Post-Harvest Quality Control",
    price: 1200,
    category: "Lab Equipment",
    description: "Portable grain moisture analyzer for maize, rice, and other cereals. Features rapid measurement, calibration for local grain varieties, and digital display with data logging.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Grain Testing Solutions",
    featured: false,
    shipping: true,
    stock: 12,
    stars: 4.3,
    reviews: 16,
    material: "Impact-resistant ABS plastic",
    designer: "Post-Harvest Technology Lab",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: false
  },
  {
    id: "rec138",
    name: "Automated Chicken Feeder - Poultry Management System",
    price: 650,
    category: "Plant Health",
    description: "Solar-powered automated chicken feeder with programmable feeding schedule. Reduces labor costs and ensures consistent feeding for optimal egg and meat production.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Poultry Automation Ghana",
    featured: false,
    shipping: true,
    stock: 20,
    stars: 4.5,
    reviews: 28,
    material: "Food-grade plastic with solar panel",
    designer: "Poultry Systems Engineering",
    bestseller: true,
    new_arrival: false,
    sale: true,
    trending: false
  },
  {
    id: "rec139",
    name: "Portable Soil Compaction Tester - Field Analysis Tool",
    price: 890,
    category: "Soil & Water",
    description: "Professional soil compaction testing device for field analysis. Measures soil density and compaction levels to optimize tillage operations and improve crop root development.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Soil Diagnostics Ghana",
    featured: true,
    shipping: true,
    stock: 8,
    stars: 4.6,
    reviews: 21,
    material: "Ruggedized steel with digital display",
    designer: "Field Testing Solutions",
    bestseller: false,
    new_arrival: true,
    sale: false,
    trending: true
  },
  {
    id: "rec140",
    name: "Weather Station with Data Logger - Complete Monitoring",
    price: 5500,
    category: "Weather Monitoring",
    description: "Comprehensive weather monitoring station with wind speed, rainfall, temperature, humidity, and barometric pressure sensors. Features cellular data transmission and cloud storage.",
    image: "/api/placeholder/400/400",
    images: [{ url: "/api/placeholder/400/400" }],
    colors: ["black", "white", "gray", "green"],
    company: "Meteorological Systems Ghana",
    featured: true,
    shipping: true,
    stock: 3,
    stars: 4.8,
    reviews: 15,
    material: "Anodized aluminum with weather-resistant sensors",
    designer: "Weather Monitoring Division",
    bestseller: true,
    new_arrival: false,
    sale: false,
    trending: true
  }
];

// Helper function to get a single product by ID
export const getFallbackProductById = (id) => {
  return fallbackProducts.find(product => product.id === id) || null;
};

// Helper function to get featured products
export const getFeaturedProducts = () => {
  return fallbackProducts.filter(product => product.featured);
};

// Helper function to get new arrival products
export const getNewArrivalProducts = () => {
  return fallbackProducts.filter(product => product.new_arrival);
};

// Helper function to get bestseller products
export const getBestsellerProducts = () => {
  return fallbackProducts.filter(product => product.bestseller);
};